version: '3'

services:
  postgres:
    image: postgres:14
    container_name: 'project3postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=111'
      - 'POSTGRES_DB=Project3'

  app:
    build: ./
    container_name: 'project3app'
    depends_on:
      - postgres
    ports:
      - "9090:9090"